// Estilos de la Mesa — portados del styles.js viejo (dark, denso, tabla compacta).
// Misma semántica de color: turquesa=recién, azul=actualizado, rojo=expirado,
// verde=mejor precio, amarillo=outlier, violeta=tiers/spread.
import type { CSSProperties } from "react";

const s = {
  page: {
    minHeight: "100vh",
    background: "#0b0e14",
    color: "#cfd6e4",
    fontFamily:
      "'SF Mono', ui-monospace, Menlo, Monaco, 'Cascadia Mono', 'Segoe UI Mono', monospace",
    fontSize: 13,
    padding: "12px 16px 40px",
  },
  header: { display: "flex", alignItems: "baseline", gap: 12, marginBottom: 10 },
  h1: { fontSize: 16, fontWeight: 700, color: "#e6ebf5", margin: 0, letterSpacing: 0.5 },
  sub: { fontSize: 11, color: "#5b657a" },

  section: {
    background: "#0e1218",
    border: "1px solid #1c2330",
    borderRadius: 8,
    padding: "10px 12px",
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 1.2,
    color: "#8b94a7",
    textTransform: "uppercase",
    marginBottom: 8,
  },

  toolbar: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", marginBottom: 10 },
  toolBtn: {
    background: "#182030",
    color: "#cfd6e4",
    border: "1px solid #273246",
    borderRadius: 5,
    padding: "4px 10px",
    fontSize: 12,
    cursor: "pointer",
  },
  toolBtnGhost: { background: "transparent", color: "#8b94a7" },
  toolBtnDisabled: { opacity: 0.45, cursor: "not-allowed" },
  toolNote: { fontSize: 11, color: "#5b657a", marginLeft: "auto" },
  numInput: {
    width: 52,
    background: "#0b0e14",
    color: "#e6ebf5",
    border: "1px solid #273246",
    borderRadius: 4,
    padding: "3px 6px",
    fontSize: 12,
    fontFamily: "inherit",
  },

  planTab: {
    background: "transparent",
    color: "#8b94a7",
    border: "1px solid #273246",
    borderRadius: 5,
    padding: "4px 12px",
    fontSize: 12.5,
    cursor: "pointer",
  },
  planTabOn: { background: "#1d2A44", color: "#e6ebf5", borderColor: "#3b4a68" },

  select: {
    background: "#0b0e14",
    color: "#e6ebf5",
    border: "1px solid #273246",
    borderRadius: 5,
    padding: "4px 8px",
    fontSize: 12.5,
    fontFamily: "inherit",
  },
  textarea: {
    width: "100%",
    boxSizing: "border-box" as const,
    background: "#0b0e14",
    color: "#e6ebf5",
    border: "1px solid #273246",
    borderRadius: 5,
    padding: "6px 8px",
    fontSize: 12.5,
    fontFamily: "inherit",
    resize: "vertical" as const,
    minHeight: 64,
  },
  textInput: {
    background: "#0b0e14",
    color: "#e6ebf5",
    border: "1px solid #273246",
    borderRadius: 5,
    padding: "4px 8px",
    fontSize: 12.5,
    fontFamily: "inherit",
  },
  primaryBtn: {
    background: "#1d4ed8",
    color: "#fff",
    border: "1px solid #2563eb",
    borderRadius: 5,
    padding: "4px 12px",
    fontSize: 12.5,
    cursor: "pointer",
  },
  busy: { opacity: 0.6, cursor: "wait" },
  okMsg: { color: "#8ee0a8", fontSize: 12, marginTop: 6 },
  errorMsg: { color: "#f87171", fontSize: 12, marginTop: 6 },
  hint: { color: "#5b657a", fontSize: 11.5, marginTop: 6 },

  tableWrap: { overflowX: "auto" as const },
  table: { borderCollapse: "collapse" as const, width: "100%", minWidth: 880 },
  th: {
    background: "#12161f",
    color: "#8b94a7",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: 0.5,
    padding: "5px 8px",
    borderBottom: "1px solid #273246",
    textAlign: "right" as const,
    whiteSpace: "nowrap" as const,
  },
  thSku: { textAlign: "left" as const, minWidth: 220 },
  thMine: { color: "#fbbf24" },
  td: { padding: "3px 8px", borderBottom: "1px solid #151b26", fontSize: 12.5 },
  tdSku: { color: "#cfd6e4", whiteSpace: "nowrap" as const },
  tdNum: { textAlign: "right" as const, color: "#e6ebf5", whiteSpace: "nowrap" as const },
  tdMuted: { color: "#8b94a7" },
  tdMine: { color: "#fbbf24", fontWeight: 600 },
  tdCell: { textAlign: "right" as const, padding: "2px 4px" },
  catRow: {
    background: "#0e1218",
    color: "#8b94a7",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 1,
    padding: "5px 8px",
    textTransform: "uppercase" as const,
  },

  // frescura / mejor / outlier — mismos colores del viejo
  cellBest: { background: "#0f2a17" },
  cellOut: { background: "#2a2410" },
  cellRecent: { background: "#0b2f30" },
  cellUpdated: { background: "#10203a" },
  cellExpired: { background: "#2a1117" },
  cellRecentBest: {
    background: "linear-gradient(135deg, #0e3536 0 47%, #0b0e14 47% 53%, #123a1d 53% 100%)",
  },
  inBest: { color: "#4ade80", fontWeight: 700 },
  inOut: { color: "#fbbf24", fontWeight: 700 },
  inRecent: { color: "#6ee7d6" },
  inUpdated: { color: "#9fb4dc" },
  inExpired: { color: "#a86b72" },

  cellInner: { display: "inline-flex", alignItems: "center", gap: 2 },
  cellInput: {
    width: 58,
    background: "transparent",
    color: "#e6ebf5",
    border: "none",
    outline: "none",
    textAlign: "right" as const,
    fontSize: 12.5,
    fontFamily: "inherit",
    padding: "2px 2px",
  },
  tierTag: {
    fontSize: 9,
    color: "#c084fc",
    marginLeft: 2,
    whiteSpace: "nowrap" as const,
    cursor: "help",
  },
  listaAuto: { color: "#7c8597", fontStyle: "italic" },
  listaSpread: { borderLeft: "2px solid #7c3aed", background: "#191526" },
  medTag: { fontSize: 10, color: "#8b94a7" },
  deltaTag: { fontSize: 10, color: "#7c8597" },
  dash: { color: "#3d4658" },

  legend: {
    display: "flex",
    flexWrap: "wrap" as const,
    gap: "6px 16px",
    fontSize: 10.5,
    color: "#8b94a7",
    marginTop: 8,
  },
  legChip: {
    display: "inline-block",
    width: 12,
    height: 12,
    borderRadius: 2,
    marginRight: 4,
    verticalAlign: "-2px",
    border: "1px solid #273246",
  },

  hideToggle: { fontSize: 11.5, color: "#8b94a7", display: "flex", alignItems: "center", gap: 5 },
  chk: { accentColor: "#2563eb" },

  // preview del parse
  previewTable: { borderCollapse: "collapse" as const, width: "100%", marginTop: 8 },
  pvTd: { padding: "3px 8px", borderBottom: "1px solid #151b26", fontSize: 12 },
  pvOld: { color: "#8b94a7", textDecoration: "line-through" },
  pvNew: { color: "#4ade80", fontWeight: 600 },
  pvName: { color: "#cfd6e4" },
  pvBadgeNew: {
    background: "#3b2a10",
    color: "#fbbf24",
    borderRadius: 3,
    fontSize: 10,
    padding: "1px 6px",
    marginLeft: 6,
  },

  // cola de confirmación
  queueItem: {
    border: "1px solid #3b2a10",
    background: "#141009",
    borderRadius: 6,
    padding: "8px 10px",
    marginBottom: 8,
  },
  queueName: { color: "#fbbf24", fontWeight: 600, fontSize: 13 },
  queueMeta: { color: "#8b94a7", fontSize: 11.5, marginTop: 2 },
  queueRow: { display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap", marginTop: 6 },
} satisfies Record<string, CSSProperties>;

export default s;
