// Sistema visual del Price Desk v2 — TOKENS EXTRAÍDOS 1:1 del styles.js del desk viejo
// (repo home): misma paleta (#0b0e14 fondo, #11151f paneles, #232a3a bordes, azul #6fa8e6
// de acentos, ámbar #fbbf24 = "mío"), misma tipografía (ui-monospace 12.5), misma densidad
// de tabla (th sticky 10.5px, filas 3px de padding), mismos colores de frescura.
// Las vistas nuevas de v2 consumen ESTOS tokens → continuidad visual inmediata.
import type { CSSProperties } from "react";

const s = {
  // ---------- shell (app / header / tabs) — del viejo: app/header/title/viewNav ----------
  page: {
    minHeight: "100vh",
    background: "#0b0e14",
    color: "#d6dae3",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    fontSize: 12.5,
    padding: "16px 20px 48px",
    boxSizing: "border-box" as const,
    transition: "padding-right .2s ease",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottom: "1px solid #1c2230",
    paddingBottom: 12,
    marginBottom: 10,
    flexWrap: "wrap" as const,
    gap: 12,
  },
  h1: { fontSize: 18, fontWeight: 700, letterSpacing: 1.5, color: "#e8ecf3", margin: 0 },
  sub: { fontSize: 11, color: "#6b7385", marginTop: 2 },
  controls: { display: "flex", gap: 14, alignItems: "flex-end", flexWrap: "wrap" as const },
  ctrlLabel: { display: "flex", flexDirection: "column" as const, gap: 4 },
  ctrlText: { fontSize: 10, color: "#6b7385", letterSpacing: 1 },
  mondayBadge: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 4,
    background: "#11151f",
    border: "1px solid #244068",
    borderRadius: 4,
    padding: "4px 10px",
  },
  mondayDate: {
    fontSize: 15,
    fontWeight: 700,
    color: "#6fa8e6",
    fontVariantNumeric: "tabular-nums" as const,
  },
  viewNav: { display: "flex", gap: 8, marginBottom: 16, flexWrap: "wrap" as const },
  viewTab: {
    background: "#11151f",
    border: "1px solid #232a3a",
    color: "#9aa3b5",
    padding: "9px 18px",
    borderRadius: 6,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 13,
    fontWeight: 600,
  },
  viewTabOn: { background: "#1e293b", borderColor: "#3b82f6", color: "#e8ecf3" },
  mesaMain: { minWidth: 0, transition: "margin-right .2s ease" },

  // ---------- secciones (flat, como el viejo: sin tarjetas) ----------
  section: { marginBottom: 20 },
  sectionTitle: {
    fontSize: 11,
    letterSpacing: 1.2,
    color: "#6b7385",
    marginBottom: 8,
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },

  // ---------- toolbar / botones / inputs ----------
  toolbar: { display: "flex", alignItems: "center", gap: 12, marginBottom: 16, flexWrap: "wrap" as const },
  toolBtn: {
    background: "#1f2937",
    border: "1px solid #2a3346",
    color: "#cfd6e4",
    padding: "5px 12px",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
  },
  toolBtnGhost: { color: "#b06a72", borderColor: "#3a1d22", background: "transparent" },
  toolBtnDisabled: { opacity: 0.45, cursor: "not-allowed" },
  toolNote: { fontSize: 10.5, color: "#6b7385" },
  miniBtn: {
    background: "#1f2937",
    border: "1px solid #2a3346",
    color: "#cfd6e4",
    padding: "3px 9px",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11,
  },
  input: {
    background: "#11151f",
    border: "1px solid #232a3a",
    color: "#e8ecf3",
    padding: "6px 8px",
    borderRadius: 4,
    fontFamily: "inherit",
    fontSize: 13,
    outline: "none",
  },
  numInput: {
    width: 52,
    background: "#0b0e14",
    border: "1px solid #232a3a",
    color: "#e8ecf3",
    borderRadius: 3,
    textAlign: "right" as const,
    fontFamily: "inherit",
    fontSize: 11,
    padding: "2px 4px",
    outline: "none",
  },
  listaFill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    color: "#9aa3b5",
  },
  select: {
    background: "#11151f",
    border: "1px solid #232a3a",
    color: "#e8ecf3",
    borderRadius: 4,
    padding: "4px 8px",
    fontFamily: "inherit",
    fontSize: 12.5,
    outline: "none",
  },
  textarea: {
    flex: 1,
    width: "100%",
    boxSizing: "border-box" as const,
    background: "#0b0e14",
    border: "1px solid #232a3a",
    color: "#cfd6e4",
    borderRadius: 4,
    padding: 8,
    fontFamily: "inherit",
    fontSize: 12,
    resize: "vertical" as const,
    outline: "none",
    lineHeight: 1.5,
  },
  textInput: {
    background: "#11151f",
    border: "1px solid #232a3a",
    color: "#e8ecf3",
    padding: "6px 8px",
    borderRadius: 4,
    fontFamily: "inherit",
    fontSize: 12.5,
    outline: "none",
  },
  primaryBtn: {
    background: "#2563eb",
    border: "none",
    color: "#fff",
    padding: "6px 16px",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 600,
    whiteSpace: "nowrap" as const,
  },
  copyBtn: {
    marginLeft: "auto",
    background: "#16a34a",
    border: "none",
    color: "#fff",
    padding: "7px 16px",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 12,
    fontWeight: 600,
  },
  busy: { background: "#374151", opacity: 0.85, cursor: "default" },
  okMsg: { fontSize: 11.5, color: "#4ade80", marginTop: 8 },
  errorMsg: {
    fontSize: 11.5,
    color: "#f87171",
    background: "#1a1014",
    border: "1px solid #3a1d22",
    borderRadius: 4,
    padding: "5px 7px",
    marginTop: 8,
    wordBreak: "break-word" as const,
  },
  hint: { fontSize: 10.5, color: "#525a6b", marginTop: 8 },
  askHint: { fontSize: 10.5, color: "#525a6b", marginTop: 8 },
  answerCard: {
    background: "#11151f",
    border: "1px solid #1c2230",
    borderRadius: 6,
    padding: 12,
    marginTop: 10,
    fontSize: 13,
    color: "#dfe4ee",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap" as const,
  },

  // ---------- tabs chicos (departamentos / modos) ----------
  planTab: {
    background: "#11151f",
    border: "1px solid #232a3a",
    color: "#9aa3b5",
    padding: "6px 12px",
    borderRadius: 4,
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: 11.5,
  },
  planTabOn: { background: "#1e293b", borderColor: "#3b82f6", color: "#e8ecf3", fontWeight: 600 },

  // ---------- tabla (densidad y sticky del viejo) ----------
  tableBar: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap" as const,
    marginBottom: 10,
  },
  markGroup: { display: "inline-flex", alignItems: "center", gap: 5, flexWrap: "wrap" as const },
  hideCount: { color: "#525a6b", fontSize: 11 },
  tableWrap: {
    overflowX: "auto" as const,
    border: "1px solid #1c2230",
    borderRadius: 6,
    maxHeight: "70vh",
    overflowY: "auto" as const,
  },
  table: { borderCollapse: "collapse" as const, width: "100%", minWidth: 880 },
  th: {
    background: "#11151f",
    color: "#8b94a7",
    fontSize: 10.5,
    fontWeight: 600,
    textAlign: "right" as const,
    padding: "8px 8px",
    borderBottom: "1px solid #1c2230",
    whiteSpace: "nowrap" as const,
    position: "sticky" as const,
    top: 0,
    zIndex: 1,
  },
  thSku: { textAlign: "left" as const, position: "sticky" as const, left: 0, zIndex: 2 },
  thMine: { color: "#fbbf24" },
  td: { padding: "3px 8px", borderBottom: "1px solid #151a26", whiteSpace: "nowrap" as const },
  tdSku: {
    textAlign: "left" as const,
    color: "#cfd6e4",
    fontWeight: 600,
    position: "sticky" as const,
    left: 0,
    background: "#0b0e14",
    zIndex: 1,
  },
  tdCell: { padding: "2px 4px", textAlign: "right" as const },
  tdNum: {
    textAlign: "right" as const,
    fontVariantNumeric: "tabular-nums" as const,
    color: "#cfd6e4",
  },
  tdMuted: { color: "#7b8499" },
  tdMine: {
    color: "#fbbf24",
    fontWeight: 700,
    background: "#15130a",
    textAlign: "right" as const,
  },
  catRow: {
    background: "#0e1218",
    color: "#8b94a7",
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: 1,
    padding: "5px 8px",
    textTransform: "uppercase" as const,
    position: "sticky" as const,
    left: 0,
  },
  cellInner: { display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 2 },
  cellInput: {
    width: 58,
    background: "transparent",
    border: "1px solid transparent",
    color: "#cfd6e4",
    textAlign: "right" as const,
    fontFamily: "inherit",
    fontSize: 12,
    padding: "3px 4px",
    borderRadius: 3,
    outline: "none",
    fontVariantNumeric: "tabular-nums" as const,
  },

  // frescura / mejor / outlier — EXACTOS del viejo
  cellBest: { background: "#0f2a17" },
  cellOut: { background: "#2a2410" },
  cellRecent: { background: "#0b2f30" },
  cellUpdated: { background: "#10203a" },
  cellExpired: { background: "#2a1117" },
  cellRecentBest: {
    background: "linear-gradient(135deg, #0e3536 0 47%, #0b0e14 47% 53%, #123a1d 53% 100%)",
  },
  inBest: { color: "#4ade80", fontWeight: 700 },
  inOut: { color: "#fbbf24", fontWeight: 700 },
  inRecent: { color: "#6ee7d6" },
  inUpdated: { color: "#9fb4dc" },
  inExpired: { color: "#a86b72" },

  tierTag: { fontSize: 9, color: "#a78bfa", marginLeft: 2, whiteSpace: "nowrap" as const, cursor: "help" },
  listaAuto: { color: "#7c8597", fontStyle: "italic" },
  listaSpread: { borderLeft: "2px solid #7c3aed", background: "#191526" },
  medTag: { fontSize: 9, color: "#a87f2a" },
  deltaTag: { color: "#a78bfa", fontSize: 9, marginLeft: 2 },
  dash: { color: "#3b4252" },

  legend: {
    display: "flex",
    gap: 16,
    flexWrap: "wrap" as const,
    fontSize: 10,
    color: "#6b7385",
    marginTop: 8,
    alignItems: "center",
  },
  legChip: {
    display: "inline-block",
    width: 11,
    height: 11,
    borderRadius: 2,
    marginRight: 4,
    verticalAlign: "-1px",
  },

  hideToggle: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11.5,
    color: "#9aa3b5",
    cursor: "pointer",
  },
  chk: { accentColor: "#3b82f6", cursor: "pointer", width: 13, height: 13 },

  // ---------- cotización al cliente (WhatsApp) ----------
  quoteBar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 12,
    flexWrap: "wrap" as const,
  },
  quotePreviewLabel: { fontSize: 10.5, color: "#6b7385", marginBottom: 4 },
  quotePreview: {
    background: "#0b0e14",
    border: "1px solid #232a3a",
    borderRadius: 6,
    padding: 12,
    fontFamily: "inherit",
    fontSize: 12.5,
    color: "#dfe4ee",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap" as const,
    margin: 0,
    overflowX: "auto" as const,
  },

  // ---------- preview del parse ----------
  previewTable: { borderCollapse: "collapse" as const, width: "100%", marginTop: 8 },
  pvTd: { padding: "3px 8px", borderBottom: "1px solid #151a26", fontSize: 12 },
  pvOld: { color: "#7b8499", textDecoration: "line-through" },
  pvNew: { color: "#4ade80", fontWeight: 600 },
  pvName: { color: "#cfd6e4" },
  pvBadgeNew: {
    background: "#3b2a10",
    color: "#fbbf24",
    borderRadius: 3,
    fontSize: 10,
    padding: "1px 6px",
    marginLeft: 6,
  },

  // ---------- cola de confirmación (feature nueva, vestida con el sistema viejo) ----------
  queueItem: {
    border: "1px solid #244068",
    background: "#11151f",
    borderRadius: 6,
    padding: "8px 10px",
    marginBottom: 8,
  },
  queueName: { color: "#fbbf24", fontWeight: 600, fontSize: 12.5 },
  queueMeta: { color: "#8b94a7", fontSize: 11, marginTop: 2 },
  queueRow: { display: "flex", gap: 6, alignItems: "center", flexWrap: "wrap" as const, marginTop: 6 },

  // ---------- chat lateral del agente (chatBox del viejo, 1:1) ----------
  chatBox: {
    position: "fixed" as const,
    top: 0,
    right: 0,
    height: "100vh",
    width: 360,
    boxSizing: "border-box" as const,
    display: "flex",
    flexDirection: "column" as const,
    background: "#0f1420",
    borderLeft: "1px solid #22304a",
    padding: 14,
    zIndex: 40,
    transition: "transform .2s ease",
  },
  chatHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 11,
    letterSpacing: 1,
    color: "#6fa8e6",
    fontWeight: 700,
    marginBottom: 8,
  },
  chatCollapse: {
    background: "transparent",
    border: "1px solid #22304a",
    color: "#9aa4b2",
    borderRadius: 4,
    cursor: "pointer",
    padding: "1px 8px",
    fontSize: 13,
  },
  chatReopen: {
    position: "fixed" as const,
    top: "50%",
    right: 0,
    transform: "translateY(-50%)",
    background: "#0f1420",
    border: "1px solid #22304a",
    borderRight: "none",
    color: "#6fa8e6",
    borderRadius: "8px 0 0 8px",
    cursor: "pointer",
    padding: "16px 7px",
    fontSize: 15,
    zIndex: 40,
    writingMode: "vertical-rl" as const,
    letterSpacing: 1,
    fontFamily: "inherit",
  },
  chatResults: {
    flex: 1,
    overflowY: "auto" as const,
    marginTop: 8,
    display: "flex",
    flexDirection: "column" as const,
    gap: 8,
  },
  chatEmpty: {
    fontSize: 12,
    color: "#6b7385",
    lineHeight: 1.5,
    border: "1px dashed #22304a",
    borderRadius: 6,
    padding: 12,
    background: "#0b0e14",
  },
  agYou: {
    alignSelf: "flex-end" as const,
    maxWidth: "90%",
    background: "#1d2740",
    border: "1px solid #2f4166",
    color: "#dbe6f7",
    borderRadius: "8px 8px 2px 8px",
    padding: "6px 9px",
    fontSize: 12.5,
    whiteSpace: "pre-wrap" as const,
  },
  agBot: {
    background: "#0f1a12",
    border: "1px solid #244a2c",
    color: "#d7ead9",
    borderRadius: "8px 8px 8px 2px",
    padding: "7px 10px",
    fontSize: 12.5,
    whiteSpace: "pre-wrap" as const,
    lineHeight: 1.45,
  },
  agTool: { fontSize: 10.5, color: "#7c8597", fontStyle: "italic", padding: "0 2px" },
  chatInputWrap: {
    flexShrink: 0,
    paddingTop: 10,
    borderTop: "1px solid #1c2230",
    marginTop: 8,
  },
  chatInput: {
    width: "100%",
    boxSizing: "border-box" as const,
    background: "#0b0e14",
    border: "1px solid #232a3a",
    color: "#e8ecf3",
    borderRadius: 4,
    padding: "8px 9px",
    fontFamily: "inherit",
    fontSize: 12.5,
    outline: "none",
  },
  newWrap: {
    marginTop: 10,
    background: "#11151f",
    border: "1px solid #244068",
    borderRadius: 6,
    padding: 10,
  },
} satisfies Record<string, CSSProperties>;

export default s;
